### PR TITLE
Remove console-app-2

### PR DESCRIPTION
**Pull request by vitaliyworks**

### CODE REVIEW

**Review by wachulski — APPROVED** [review]
lgtm, very good delta :)

**Comment by egorgripasov** [comment]
@vitaliyworks no `yarn.lock` changes?

**Comment by vitaliyworks** [comment]
@egorgripasov I did not think about `yarn.lock`. Let me check now

**Comment by vitaliyworks** [comment]
@egorgripasov you are right, there were changes to yarn.lock. I commited them now

**Comment by vitaliyworks** [comment]
Actually... This break konsole-app build for me. Investigating...

**Comment by vitaliyworks** [comment]
Ok, those build errors were coming from missing packages in `konsole-app/package.json`. I added them now and everything works. Could you please test the build as well @egorgripasov @wachulski ?

**Comment by richburdon** [comment]
@vitaliyworks if you just remove the yarn.lock file and rebuild you should be able to test this fine -- or if your branch is committed then git clean -xdf and rebuild (removes all non git files like node_modules).

**Comment by vitaliyworks** [comment]
@richburdon I did `git clean -dfx` and rebuild, but still not sure... :)

**Comment by egorgripasov** [comment]
@vitaliywork you should be good then;
app builds&starts for me - please merge the PR

**Pull request merged**
